name: Redeploy Backend

on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/**'

jobs:
  redeploy-backend:
    name: Rebuild and Deploy Backend
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          
      - name: Configure Docker to use GCR
        run: gcloud auth configure-docker

      - name: Build Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/proj-mgmt-bck-app:${{ github.sha }} \
            backend

      - name: Push Docker Image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/proj-mgmt-bck-app:${{ github.sha }}

      - name: Update Cloud Run Service
        run: |
          gcloud run deploy my-nodejs-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/proj-mgmt-bck-app:${{ github.sha }} \
            --region us-east1 \
            --platform managed