name: Deploy Infrastructure to Google Cloud

on:
  push:
    branches:
      - main 

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Step 3: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform -chdir=infrastructure/terraform init

      # Step 5: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -chdir=infrastructure/terraform -out=tfplan \
             -var="gcp_project=${{ secrets.GCP_PROJECT }}" \
             -var="gcp_region=${{ secrets.GCP_REGION }}"

      # Step 6: Terraform Apply
      - name: Terraform Apply
        if: success()
        run: terraform -chdir=infrastructure/terraform apply -auto-approve tfplan