name: Debug OIDC Token

on:
  workflow_dispatch: # Allows manual triggering of this workflow

jobs:
  debug-oidc:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check Out Repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Request OIDC Token
      - name: Request OIDC Token
        id: oidc-token
        run: |
          # Fetch the OIDC token
          echo "Requesting OIDC token..."
          curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" > oidc-token.json

          # Log the raw token for inspection (ensure this is private for security)
          echo "Raw OIDC token stored in oidc-token.json"

      # Step 3: Decode OIDC Token
      - name: Decode and Log OIDC Token
        run: |
          # Decode and log the token's payload using jq
          echo "Decoding OIDC token..."
          cat oidc-token.json | jq '.'

      # Step 4: Debug Environment Variables
      - name: Debug Environment Variables
        run: printenv